name: mmargel-aoc-2020

type: node

up:
  - node:
      version: v12.18.4
      yarn: true
      packages:
        - .
        # - path/to/other/package

commands:
  test: yarn test
  server: yarn dev
  setup: yarn setup
